CREATE TABLE usuario
(
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo       VARCHAR(31)                             NOT NULL,
    login      VARCHAR(255)                            NOT NULL,
    senha      VARCHAR(255),
    nome       VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    telefone   VARCHAR(255),
    rua        VARCHAR(255),
    numero     VARCHAR(255),
    bairro     VARCHAR(255),
    cidade     VARCHAR(255),
    estado     VARCHAR(255),
    cep        VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_login UNIQUE (login);